#!/bin/bash

#PBS -N myjob | #SBATCH —job-name=myjob
#PBS -l walltime=1:00:00 | #SBATCH —time=1:00:00
#PBS -l nodes=N:ppn=M | #SBATCH —nodes=N —ntasks-per-node=M
#PBS -l mem=Xgb | #SBATCH —mem=Xgb
#PBS -l pmem=Xgb | #SBATCH —mem-per-cpu=Xgb
#PBS -q queue | #SBATCH —partition queue
#PBS -l fearute=mem32 | #SBATCH —constraint=mem32 

qsub <jobscript> | sbatch <jobscript>
qdel <jobid> | scancel <jobid>
qstat -u <user> | squeue -u <user> 

